class CourseItems {
  final String title,
      name,
      price,
      priceSale,
      image,
      discount,
      tag,
      level,
      lesson,
      time,
  certificate,
  intro,
  information
  ;
  CourseItems(
      {this.title,
      this.name,
      this.priceSale,
      this.price,
      this.image,
      this.discount,
      this.tag,
      this.time,
      this.lesson,
        this.certificate,
      this.level,
      this.intro,
        this.information

      });
}

List<CourseItems> allCourseItems = [
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
  CourseItems(
    title: 'Xây dựng hệ thống bền vững Xây dựng hệ thống bền vững',
    name: 'Nguyễn Văn A',
    priceSale: '199.999đ',
    price: '199.999đ',
    image: 'assets/images/img_nongnghiep.jpg',
    discount: '25%',
    tag: 'Text-Audio',
    level: 'A1',
    lesson: '16 bài',
    time: 'Mãi Mãi',
      certificate: 'TOEIC',
    intro: 'Chương trình đào tạo này được thiết kế nhằm cung cấp kiến thức và kinh nghiệm giúp người học có khả năng tự thành lập một cửa hàng kinh doanh tại nhà một cách hiệu quả. Thông qua các chuyên đề được cung cấp trong chương trình, người học có đủ kiến thức để quản lý và tạo lập được các mối quan hệ trong kinh doanh, duy trì và phát triển cửa hàng kinh doanh và gia tăng doanh thu, cải thiện kinh tế gia đình',
  ),
];
